/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './../pages/__root'
import { Route as IndexRouteImport } from './../pages/index'

const WordCounterIndexLazyRouteImport = createFileRoute('/word-counter/')()
const UrlEncoderDecoderIndexLazyRouteImport = createFileRoute(
  '/url-encoder-decoder/',
)()
const TimestampToDateIndexLazyRouteImport = createFileRoute(
  '/timestamp-to-date/',
)()
const TextGeneratorIndexLazyRouteImport = createFileRoute('/text-generator/')()
const TextDiffViewerIndexLazyRouteImport =
  createFileRoute('/text-diff-viewer/')()
const StringConverterIndexLazyRouteImport =
  createFileRoute('/string-converter/')()
const ResumeIndexLazyRouteImport = createFileRoute('/resume/')()
const RegexLibraryIndexLazyRouteImport = createFileRoute('/regex-library/')()
const QueryParamsParserIndexLazyRouteImport = createFileRoute(
  '/query-params-parser/',
)()
const OnKeyDownIndexLazyRouteImport = createFileRoute('/on-key-down/')()
const NpmScriptIndexLazyRouteImport = createFileRoute('/npm-script/')()
const MinifyPrettifyIndexLazyRouteImport =
  createFileRoute('/minify-prettify/')()
const MetaGeneratorIndexLazyRouteImport = createFileRoute('/meta-generator/')()
const MermaidViewerIndexLazyRouteImport = createFileRoute('/mermaid-viewer/')()
const MarkdownViewerIndexLazyRouteImport =
  createFileRoute('/markdown-viewer/')()
const JwtDecoderIndexLazyRouteImport = createFileRoute('/jwt-decoder/')()
const JsonViewerIndexLazyRouteImport = createFileRoute('/json-viewer/')()
const JavascriptRegexTestIndexLazyRouteImport = createFileRoute(
  '/javascript-regex-test/',
)()
const ImageConverterIndexLazyRouteImport =
  createFileRoute('/image-converter/')()
const CsvViewerIndexLazyRouteImport = createFileRoute('/csv-viewer/')()
const ColorConverterIndexLazyRouteImport =
  createFileRoute('/color-converter/')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WordCounterIndexLazyRoute = WordCounterIndexLazyRouteImport.update({
  id: '/word-counter/',
  path: '/word-counter/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./../pages/word-counter/index.lazy').then((d) => d.Route),
)
const UrlEncoderDecoderIndexLazyRoute =
  UrlEncoderDecoderIndexLazyRouteImport.update({
    id: '/url-encoder-decoder/',
    path: '/url-encoder-decoder/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./../pages/url-encoder-decoder/index.lazy').then((d) => d.Route),
  )
const TimestampToDateIndexLazyRoute =
  TimestampToDateIndexLazyRouteImport.update({
    id: '/timestamp-to-date/',
    path: '/timestamp-to-date/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./../pages/timestamp-to-date/index.lazy').then((d) => d.Route),
  )
const TextGeneratorIndexLazyRoute = TextGeneratorIndexLazyRouteImport.update({
  id: '/text-generator/',
  path: '/text-generator/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./../pages/text-generator/index.lazy').then((d) => d.Route),
)
const TextDiffViewerIndexLazyRoute = TextDiffViewerIndexLazyRouteImport.update({
  id: '/text-diff-viewer/',
  path: '/text-diff-viewer/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./../pages/text-diff-viewer/index.lazy').then((d) => d.Route),
)
const StringConverterIndexLazyRoute =
  StringConverterIndexLazyRouteImport.update({
    id: '/string-converter/',
    path: '/string-converter/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./../pages/string-converter/index.lazy').then((d) => d.Route),
  )
const ResumeIndexLazyRoute = ResumeIndexLazyRouteImport.update({
  id: '/resume/',
  path: '/resume/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./../pages/resume/index.lazy').then((d) => d.Route),
)
const RegexLibraryIndexLazyRoute = RegexLibraryIndexLazyRouteImport.update({
  id: '/regex-library/',
  path: '/regex-library/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./../pages/regex-library/index.lazy').then((d) => d.Route),
)
const QueryParamsParserIndexLazyRoute =
  QueryParamsParserIndexLazyRouteImport.update({
    id: '/query-params-parser/',
    path: '/query-params-parser/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./../pages/query-params-parser/index.lazy').then((d) => d.Route),
  )
const OnKeyDownIndexLazyRoute = OnKeyDownIndexLazyRouteImport.update({
  id: '/on-key-down/',
  path: '/on-key-down/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./../pages/on-key-down/index.lazy').then((d) => d.Route),
)
const NpmScriptIndexLazyRoute = NpmScriptIndexLazyRouteImport.update({
  id: '/npm-script/',
  path: '/npm-script/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./../pages/npm-script/index.lazy').then((d) => d.Route),
)
const MinifyPrettifyIndexLazyRoute = MinifyPrettifyIndexLazyRouteImport.update({
  id: '/minify-prettify/',
  path: '/minify-prettify/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./../pages/minify-prettify/index.lazy').then((d) => d.Route),
)
const MetaGeneratorIndexLazyRoute = MetaGeneratorIndexLazyRouteImport.update({
  id: '/meta-generator/',
  path: '/meta-generator/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./../pages/meta-generator/index.lazy').then((d) => d.Route),
)
const MermaidViewerIndexLazyRoute = MermaidViewerIndexLazyRouteImport.update({
  id: '/mermaid-viewer/',
  path: '/mermaid-viewer/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./../pages/mermaid-viewer/index.lazy').then((d) => d.Route),
)
const MarkdownViewerIndexLazyRoute = MarkdownViewerIndexLazyRouteImport.update({
  id: '/markdown-viewer/',
  path: '/markdown-viewer/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./../pages/markdown-viewer/index.lazy').then((d) => d.Route),
)
const JwtDecoderIndexLazyRoute = JwtDecoderIndexLazyRouteImport.update({
  id: '/jwt-decoder/',
  path: '/jwt-decoder/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./../pages/jwt-decoder/index.lazy').then((d) => d.Route),
)
const JsonViewerIndexLazyRoute = JsonViewerIndexLazyRouteImport.update({
  id: '/json-viewer/',
  path: '/json-viewer/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./../pages/json-viewer/index.lazy').then((d) => d.Route),
)
const JavascriptRegexTestIndexLazyRoute =
  JavascriptRegexTestIndexLazyRouteImport.update({
    id: '/javascript-regex-test/',
    path: '/javascript-regex-test/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./../pages/javascript-regex-test/index.lazy').then((d) => d.Route),
  )
const ImageConverterIndexLazyRoute = ImageConverterIndexLazyRouteImport.update({
  id: '/image-converter/',
  path: '/image-converter/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./../pages/image-converter/index.lazy').then((d) => d.Route),
)
const CsvViewerIndexLazyRoute = CsvViewerIndexLazyRouteImport.update({
  id: '/csv-viewer/',
  path: '/csv-viewer/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./../pages/csv-viewer/index.lazy').then((d) => d.Route),
)
const ColorConverterIndexLazyRoute = ColorConverterIndexLazyRouteImport.update({
  id: '/color-converter/',
  path: '/color-converter/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./../pages/color-converter/index.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/color-converter': typeof ColorConverterIndexLazyRoute
  '/csv-viewer': typeof CsvViewerIndexLazyRoute
  '/image-converter': typeof ImageConverterIndexLazyRoute
  '/javascript-regex-test': typeof JavascriptRegexTestIndexLazyRoute
  '/json-viewer': typeof JsonViewerIndexLazyRoute
  '/jwt-decoder': typeof JwtDecoderIndexLazyRoute
  '/markdown-viewer': typeof MarkdownViewerIndexLazyRoute
  '/mermaid-viewer': typeof MermaidViewerIndexLazyRoute
  '/meta-generator': typeof MetaGeneratorIndexLazyRoute
  '/minify-prettify': typeof MinifyPrettifyIndexLazyRoute
  '/npm-script': typeof NpmScriptIndexLazyRoute
  '/on-key-down': typeof OnKeyDownIndexLazyRoute
  '/query-params-parser': typeof QueryParamsParserIndexLazyRoute
  '/regex-library': typeof RegexLibraryIndexLazyRoute
  '/resume': typeof ResumeIndexLazyRoute
  '/string-converter': typeof StringConverterIndexLazyRoute
  '/text-diff-viewer': typeof TextDiffViewerIndexLazyRoute
  '/text-generator': typeof TextGeneratorIndexLazyRoute
  '/timestamp-to-date': typeof TimestampToDateIndexLazyRoute
  '/url-encoder-decoder': typeof UrlEncoderDecoderIndexLazyRoute
  '/word-counter': typeof WordCounterIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/color-converter': typeof ColorConverterIndexLazyRoute
  '/csv-viewer': typeof CsvViewerIndexLazyRoute
  '/image-converter': typeof ImageConverterIndexLazyRoute
  '/javascript-regex-test': typeof JavascriptRegexTestIndexLazyRoute
  '/json-viewer': typeof JsonViewerIndexLazyRoute
  '/jwt-decoder': typeof JwtDecoderIndexLazyRoute
  '/markdown-viewer': typeof MarkdownViewerIndexLazyRoute
  '/mermaid-viewer': typeof MermaidViewerIndexLazyRoute
  '/meta-generator': typeof MetaGeneratorIndexLazyRoute
  '/minify-prettify': typeof MinifyPrettifyIndexLazyRoute
  '/npm-script': typeof NpmScriptIndexLazyRoute
  '/on-key-down': typeof OnKeyDownIndexLazyRoute
  '/query-params-parser': typeof QueryParamsParserIndexLazyRoute
  '/regex-library': typeof RegexLibraryIndexLazyRoute
  '/resume': typeof ResumeIndexLazyRoute
  '/string-converter': typeof StringConverterIndexLazyRoute
  '/text-diff-viewer': typeof TextDiffViewerIndexLazyRoute
  '/text-generator': typeof TextGeneratorIndexLazyRoute
  '/timestamp-to-date': typeof TimestampToDateIndexLazyRoute
  '/url-encoder-decoder': typeof UrlEncoderDecoderIndexLazyRoute
  '/word-counter': typeof WordCounterIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/color-converter/': typeof ColorConverterIndexLazyRoute
  '/csv-viewer/': typeof CsvViewerIndexLazyRoute
  '/image-converter/': typeof ImageConverterIndexLazyRoute
  '/javascript-regex-test/': typeof JavascriptRegexTestIndexLazyRoute
  '/json-viewer/': typeof JsonViewerIndexLazyRoute
  '/jwt-decoder/': typeof JwtDecoderIndexLazyRoute
  '/markdown-viewer/': typeof MarkdownViewerIndexLazyRoute
  '/mermaid-viewer/': typeof MermaidViewerIndexLazyRoute
  '/meta-generator/': typeof MetaGeneratorIndexLazyRoute
  '/minify-prettify/': typeof MinifyPrettifyIndexLazyRoute
  '/npm-script/': typeof NpmScriptIndexLazyRoute
  '/on-key-down/': typeof OnKeyDownIndexLazyRoute
  '/query-params-parser/': typeof QueryParamsParserIndexLazyRoute
  '/regex-library/': typeof RegexLibraryIndexLazyRoute
  '/resume/': typeof ResumeIndexLazyRoute
  '/string-converter/': typeof StringConverterIndexLazyRoute
  '/text-diff-viewer/': typeof TextDiffViewerIndexLazyRoute
  '/text-generator/': typeof TextGeneratorIndexLazyRoute
  '/timestamp-to-date/': typeof TimestampToDateIndexLazyRoute
  '/url-encoder-decoder/': typeof UrlEncoderDecoderIndexLazyRoute
  '/word-counter/': typeof WordCounterIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/color-converter'
    | '/csv-viewer'
    | '/image-converter'
    | '/javascript-regex-test'
    | '/json-viewer'
    | '/jwt-decoder'
    | '/markdown-viewer'
    | '/mermaid-viewer'
    | '/meta-generator'
    | '/minify-prettify'
    | '/npm-script'
    | '/on-key-down'
    | '/query-params-parser'
    | '/regex-library'
    | '/resume'
    | '/string-converter'
    | '/text-diff-viewer'
    | '/text-generator'
    | '/timestamp-to-date'
    | '/url-encoder-decoder'
    | '/word-counter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/color-converter'
    | '/csv-viewer'
    | '/image-converter'
    | '/javascript-regex-test'
    | '/json-viewer'
    | '/jwt-decoder'
    | '/markdown-viewer'
    | '/mermaid-viewer'
    | '/meta-generator'
    | '/minify-prettify'
    | '/npm-script'
    | '/on-key-down'
    | '/query-params-parser'
    | '/regex-library'
    | '/resume'
    | '/string-converter'
    | '/text-diff-viewer'
    | '/text-generator'
    | '/timestamp-to-date'
    | '/url-encoder-decoder'
    | '/word-counter'
  id:
    | '__root__'
    | '/'
    | '/color-converter/'
    | '/csv-viewer/'
    | '/image-converter/'
    | '/javascript-regex-test/'
    | '/json-viewer/'
    | '/jwt-decoder/'
    | '/markdown-viewer/'
    | '/mermaid-viewer/'
    | '/meta-generator/'
    | '/minify-prettify/'
    | '/npm-script/'
    | '/on-key-down/'
    | '/query-params-parser/'
    | '/regex-library/'
    | '/resume/'
    | '/string-converter/'
    | '/text-diff-viewer/'
    | '/text-generator/'
    | '/timestamp-to-date/'
    | '/url-encoder-decoder/'
    | '/word-counter/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColorConverterIndexLazyRoute: typeof ColorConverterIndexLazyRoute
  CsvViewerIndexLazyRoute: typeof CsvViewerIndexLazyRoute
  ImageConverterIndexLazyRoute: typeof ImageConverterIndexLazyRoute
  JavascriptRegexTestIndexLazyRoute: typeof JavascriptRegexTestIndexLazyRoute
  JsonViewerIndexLazyRoute: typeof JsonViewerIndexLazyRoute
  JwtDecoderIndexLazyRoute: typeof JwtDecoderIndexLazyRoute
  MarkdownViewerIndexLazyRoute: typeof MarkdownViewerIndexLazyRoute
  MermaidViewerIndexLazyRoute: typeof MermaidViewerIndexLazyRoute
  MetaGeneratorIndexLazyRoute: typeof MetaGeneratorIndexLazyRoute
  MinifyPrettifyIndexLazyRoute: typeof MinifyPrettifyIndexLazyRoute
  NpmScriptIndexLazyRoute: typeof NpmScriptIndexLazyRoute
  OnKeyDownIndexLazyRoute: typeof OnKeyDownIndexLazyRoute
  QueryParamsParserIndexLazyRoute: typeof QueryParamsParserIndexLazyRoute
  RegexLibraryIndexLazyRoute: typeof RegexLibraryIndexLazyRoute
  ResumeIndexLazyRoute: typeof ResumeIndexLazyRoute
  StringConverterIndexLazyRoute: typeof StringConverterIndexLazyRoute
  TextDiffViewerIndexLazyRoute: typeof TextDiffViewerIndexLazyRoute
  TextGeneratorIndexLazyRoute: typeof TextGeneratorIndexLazyRoute
  TimestampToDateIndexLazyRoute: typeof TimestampToDateIndexLazyRoute
  UrlEncoderDecoderIndexLazyRoute: typeof UrlEncoderDecoderIndexLazyRoute
  WordCounterIndexLazyRoute: typeof WordCounterIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/word-counter/': {
      id: '/word-counter/'
      path: '/word-counter'
      fullPath: '/word-counter'
      preLoaderRoute: typeof WordCounterIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/url-encoder-decoder/': {
      id: '/url-encoder-decoder/'
      path: '/url-encoder-decoder'
      fullPath: '/url-encoder-decoder'
      preLoaderRoute: typeof UrlEncoderDecoderIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timestamp-to-date/': {
      id: '/timestamp-to-date/'
      path: '/timestamp-to-date'
      fullPath: '/timestamp-to-date'
      preLoaderRoute: typeof TimestampToDateIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-generator/': {
      id: '/text-generator/'
      path: '/text-generator'
      fullPath: '/text-generator'
      preLoaderRoute: typeof TextGeneratorIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-diff-viewer/': {
      id: '/text-diff-viewer/'
      path: '/text-diff-viewer'
      fullPath: '/text-diff-viewer'
      preLoaderRoute: typeof TextDiffViewerIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/string-converter/': {
      id: '/string-converter/'
      path: '/string-converter'
      fullPath: '/string-converter'
      preLoaderRoute: typeof StringConverterIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/': {
      id: '/resume/'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regex-library/': {
      id: '/regex-library/'
      path: '/regex-library'
      fullPath: '/regex-library'
      preLoaderRoute: typeof RegexLibraryIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query-params-parser/': {
      id: '/query-params-parser/'
      path: '/query-params-parser'
      fullPath: '/query-params-parser'
      preLoaderRoute: typeof QueryParamsParserIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/on-key-down/': {
      id: '/on-key-down/'
      path: '/on-key-down'
      fullPath: '/on-key-down'
      preLoaderRoute: typeof OnKeyDownIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/npm-script/': {
      id: '/npm-script/'
      path: '/npm-script'
      fullPath: '/npm-script'
      preLoaderRoute: typeof NpmScriptIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minify-prettify/': {
      id: '/minify-prettify/'
      path: '/minify-prettify'
      fullPath: '/minify-prettify'
      preLoaderRoute: typeof MinifyPrettifyIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta-generator/': {
      id: '/meta-generator/'
      path: '/meta-generator'
      fullPath: '/meta-generator'
      preLoaderRoute: typeof MetaGeneratorIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mermaid-viewer/': {
      id: '/mermaid-viewer/'
      path: '/mermaid-viewer'
      fullPath: '/mermaid-viewer'
      preLoaderRoute: typeof MermaidViewerIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markdown-viewer/': {
      id: '/markdown-viewer/'
      path: '/markdown-viewer'
      fullPath: '/markdown-viewer'
      preLoaderRoute: typeof MarkdownViewerIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jwt-decoder/': {
      id: '/jwt-decoder/'
      path: '/jwt-decoder'
      fullPath: '/jwt-decoder'
      preLoaderRoute: typeof JwtDecoderIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-viewer/': {
      id: '/json-viewer/'
      path: '/json-viewer'
      fullPath: '/json-viewer'
      preLoaderRoute: typeof JsonViewerIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/javascript-regex-test/': {
      id: '/javascript-regex-test/'
      path: '/javascript-regex-test'
      fullPath: '/javascript-regex-test'
      preLoaderRoute: typeof JavascriptRegexTestIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-converter/': {
      id: '/image-converter/'
      path: '/image-converter'
      fullPath: '/image-converter'
      preLoaderRoute: typeof ImageConverterIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csv-viewer/': {
      id: '/csv-viewer/'
      path: '/csv-viewer'
      fullPath: '/csv-viewer'
      preLoaderRoute: typeof CsvViewerIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color-converter/': {
      id: '/color-converter/'
      path: '/color-converter'
      fullPath: '/color-converter'
      preLoaderRoute: typeof ColorConverterIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColorConverterIndexLazyRoute: ColorConverterIndexLazyRoute,
  CsvViewerIndexLazyRoute: CsvViewerIndexLazyRoute,
  ImageConverterIndexLazyRoute: ImageConverterIndexLazyRoute,
  JavascriptRegexTestIndexLazyRoute: JavascriptRegexTestIndexLazyRoute,
  JsonViewerIndexLazyRoute: JsonViewerIndexLazyRoute,
  JwtDecoderIndexLazyRoute: JwtDecoderIndexLazyRoute,
  MarkdownViewerIndexLazyRoute: MarkdownViewerIndexLazyRoute,
  MermaidViewerIndexLazyRoute: MermaidViewerIndexLazyRoute,
  MetaGeneratorIndexLazyRoute: MetaGeneratorIndexLazyRoute,
  MinifyPrettifyIndexLazyRoute: MinifyPrettifyIndexLazyRoute,
  NpmScriptIndexLazyRoute: NpmScriptIndexLazyRoute,
  OnKeyDownIndexLazyRoute: OnKeyDownIndexLazyRoute,
  QueryParamsParserIndexLazyRoute: QueryParamsParserIndexLazyRoute,
  RegexLibraryIndexLazyRoute: RegexLibraryIndexLazyRoute,
  ResumeIndexLazyRoute: ResumeIndexLazyRoute,
  StringConverterIndexLazyRoute: StringConverterIndexLazyRoute,
  TextDiffViewerIndexLazyRoute: TextDiffViewerIndexLazyRoute,
  TextGeneratorIndexLazyRoute: TextGeneratorIndexLazyRoute,
  TimestampToDateIndexLazyRoute: TimestampToDateIndexLazyRoute,
  UrlEncoderDecoderIndexLazyRoute: UrlEncoderDecoderIndexLazyRoute,
  WordCounterIndexLazyRoute: WordCounterIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
